const projects = [
  {
    "slug": "ncc-monorail-depot-buildings",
    "name": "NCC Monorail Depot Buildings",
    "name_ar": "مباني مستودعات مونوريل العاصمة الإدارية",
    "name_it": "Edifici del Deposito Monorotaia NCC",
    "name_fr": "Bâtiments du dépôt du monorail NCC",
    "subtitle": "Ergonomic and O&M Furniture",
    "subtitle_ar": "أثاث مريح ومعدات التشغيل والصيانة",
    "subtitle_it": "Mobili Ergonomici e O&M",
    "subtitle_fr": "Mobilier ergonomique et d'exploitation-maintenance",
    "sector": "Transport / Control Room",
    "sector_ar": "النقل / غرف التحكم",
    "sector_it": "Trasporti / Sala di Controllo",
    "sector_fr": "Transport / Salle de contrôle",
    "location": "New Capital City · New Cairo · Nasr City",
    "location_ar": "العاصمة الإدارية · القاهرة الجديدة · مدينة نصر",
    "location_it": "Nuova Capitale · Nuova Cairo · Nasr City",
    "location_fr": "Nouvelle Capitale · Nouveau Caire · Nasr City",
    "image": "/images/our-projects/ncc-monorail-depot-buildings/100_4770.JPG",
    "description": "Supply and installation of ergonomic and O&M furniture for the NCC Monorail Depot Buildings across three sites — New Capital City, New Cairo, and Nasr City. Furniture was specified to meet the demanding 24/7 operational requirements of depot environments, covering workstations, operator consoles, storage, and administrative areas throughout each facility.",
    "description_ar": "توريد وتركيب أثاث مريح ومعدات التشغيل والصيانة لمباني مستودعات مونوريل العاصمة عبر ثلاثة مواقع: العاصمة الإدارية، القاهرة الجديدة، ومدينة نصر. تم تحديد الأثاث لتلبية متطلبات التشغيل الصعبة على مدار 24 ساعة طوال أيام الأسبوع لبيئات المستودعات، وتغطية محطات العمل ووحدات تحكم المشغلين والتخزين والمناطق الإدارية في كل منشأة.",
    "description_it": "Fornitura e installazione di mobili ergonomici e O&M per gli edifici del deposito della monorotaia NCC in tre siti: Nuova Capitale, Nuova Cairo e Nasr City. I mobili sono stati specificati per soddisfare i rigorosi requisiti operativi 24/7 degli ambienti del deposito, coprendo postazioni di lavoro, console operatore, aree di archiviazione e amministrative in ogni struttura.",
    "description_fr": "Fourniture et installation de mobilier ergonomique et d'exploitation-maintenance pour les bâtiments du dépôt du monorail NCC sur trois sites : Nouvelle Capitale, Nouveau Caire et Nasr City. Le mobilier a été spécifié pour répondre aux exigences opérationnelles contraignantes 24h/24 et 7j/7 des environnements de dépôt, couvrant les postes de travail, les consoles opérateurs, les zones de stockage et les espaces administratifs de chaque installation.",
    "gallery": [
      "/images/our-projects/ncc-monorail-depot-buildings/100_4770.JPG",
      "/images/our-projects/ncc-monorail-depot-buildings/100_4666.JPG",
      "/images/our-projects/ncc-monorail-depot-buildings/100_4699.JPG",
      "/images/our-projects/ncc-monorail-depot-buildings/100_4999.jpg",
      "/images/our-projects/ncc-monorail-depot-buildings/8.jpg"
    ]
  },
  {
    "slug": "ncc-monorail-stations",
    "name": "NCC Monorail Stations",
    "name_ar": "محطات مونوريل العاصمة الإدارية",
    "name_it": "Stazioni Monorotaia NCC",
    "name_fr": "Stations du monorail NCC",
    "subtitle": "Ergonomic and O&M Furniture",
    "subtitle_ar": "أثاث مريح ومعدات التشغيل والصيانة",
    "subtitle_it": "Mobili Ergonomici e O&M",
    "subtitle_fr": "Mobilier ergonomique et d'exploitation-maintenance",
    "sector": "Transport / Control Room",
    "sector_ar": "النقل / غرف التحكم",
    "sector_it": "Trasporti / Sala di Controllo",
    "sector_fr": "Transport / Salle de contrôle",
    "location": "New Capital City · New Cairo · Nasr City",
    "location_ar": "العاصمة الإدارية · القاهرة الجديدة · مدينة نصر",
    "location_it": "Nuova Capitale · Nuova Cairo · Nasr City",
    "location_fr": "Nouvelle Capitale · Nouveau Caire · Nasr City",
    "image": "/images/our-projects/ncc-monorail-stations/STATION ELEVATION.JPG",
    "description": "Supply and installation of ergonomic and O&M furniture for the NCC Monorail Stations across three sites — New Capital City, New Cairo, and Nasr City. Furniture was specified to meet the demanding operational requirements of monorail station environments.",
    "description_ar": "توريد وتركيب أثاث مريح ومعدات التشغيل والصيانة لمحطات مونوريل العاصمة عبر ثلاثة مواقع: العاصمة الإدارية، القاهرة الجديدة، ومدينة نصر. تم تحديد الأثاث لتلبية متطلبات التشغيل الصعبة لبيئات محطات المونوريل.",
    "description_it": "Fornitura e installazione di mobili ergonomici e O&M per le stazioni della monorotaia NCC in tre siti: Nuova Capitale, Nuova Cairo e Nasr City. I mobili sono stati specificati per soddisfare i rigorosi requisiti operativi degli ambienti delle stazioni della monorotaia.",
    "description_fr": "Fourniture et installation de mobilier ergonomique et d'exploitation-maintenance pour les stations du monorail NCC sur trois sites : Nouvelle Capitale, Nouveau Caire et Nasr City. Le mobilier a été spécifié pour répondre aux exigences opérationnelles contraignantes des environnements de stations de monorail.",
    "gallery": [
      "/images/our-projects/ncc-monorail-stations/STATION ELEVATION.JPG",
      "/images/our-projects/ncc-monorail-stations/108 - TOM 2.JPG",
      "/images/our-projects/ncc-monorail-stations/116 - SMO.JPG",
      "/images/our-projects/ncc-monorail-stations/132 - SPARE ROOM.JPG"
    ]
  },
  {
    "slug": "west-nile-monorail",
    "name": "West Nile Monorail",
    "name_ar": "مونوريل غرب النيل",
    "name_it": "Monorotaia del Nilo Occidentale",
    "name_fr": "Monorail de West Nile",
    "subtitle": "OCC Control Consoles",
    "subtitle_ar": "وحدات تحكم المشغلين (OCC)",
    "subtitle_it": "Console di Controllo OCC",
    "subtitle_fr": "Consoles de contrôle OCC",
    "sector": "Transport / Control Room",
    "sector_ar": "النقل / غرف التحكم",
    "sector_it": "Trasporti / Sala di Controllo",
    "sector_fr": "Transport / Salle de contrôle",
    "location": "Giza · 6th of October City",
    "location_ar": "الجيزة · مدينة 6 أكتوبر",
    "location_it": "Giza · Città del 6 Ottobre",
    "location_fr": "Gizeh · Ville du 6 Octobre",
    "image": "/images/our-projects/west-nile-monorail/mono.jpg",
    "description": "Supply and installation of OCC control consoles for the West Nile Monorail project across Giza and 6th of October City. Custom-configured operator consoles designed to meet the demanding 24/7 operational requirements of monorail control environments.",
    "description_ar": "توريد وتركيب وحدات تحكم المشغلين لمشروع مونوريل غرب النيل عبر الجيزة ومدينة 6 أكتوبر. وحدات تحكم مشغلين مخصصة تم تصميمها لتلبية متطلبات التشغيل الصعبة على مدار 24 ساعة طوال أيام الأسبوع لبيئات التحكم في المونوريل.",
    "description_it": "Fornitura e installazione di console di controllo OCC per il progetto della monorotaia del Nilo Occidentale a Giza e nella Città del 6 Ottobre. Console operatore configurate su misura e progettate per soddisfare i rigorosi requisiti operativi 24/7 degli ambienti di controllo della monorotaia.",
    "description_fr": "Fourniture et installation de consoles de contrôle OCC pour le projet du monorail de West Nile à Gizeh et dans la Ville du 6 Octobre. Consoles opérateurs configurées sur mesure et conçues pour répondre aux exigences opérationnelles contraignantes 24h/24 et 7j/7 des environnements de contrôle de monorail.",
    "gallery": [
      "/images/our-projects/west-nile-monorail/mono.jpg",
      "/images/our-projects/west-nile-monorail/100_4944.jpeg",
      "/images/our-projects/west-nile-monorail/100_5920.jpg",
      "/images/our-projects/west-nile-monorail/100_5939.jpg"
    ]
  },
  {
    "slug": "west-nile-monorail-furniture",
    "name": "West Nile Monorail Furniture",
    "name_ar": "أثاث مونوريل غرب النيل",
    "name_it": "Mobili Monorotaia Nilo Occidentale",
    "name_fr": "Mobilier du monorail de West Nile",
    "sector": "Transport",
    "sector_ar": "النقل",
    "sector_it": "Trasporti",
    "sector_fr": "Transport",
    "location": "Egypt",
    "location_ar": "مصر",
    "location_it": "Egitto",
    "location_fr": "Égypte",
    "image": "/images/office.png",
    "description": "Furniture supply for the West Nile monorail project, including station and operational facility furnishings. Delivered to the same quality standards as the NCC monorail project.",
    "description_ar": "توريد الأثاث لمشروع مونوريل غرب النيل، بما في ذلك أثاث المحطات والمرافق التشغيلية. تم التسليم بنفس معايير الجودة المطبقة في مشروع مونوريل العاصمة.",
    "description_it": "Fornitura di mobili per il progetto della monorotaia del Nilo Occidentale, inclusi gli arredi delle stazioni e delle strutture operative. Consegnati con gli stessi standard di qualità del progetto della monorotaia NCC.",
    "description_fr": "Fourniture de mobilier pour le projet du monorail de West Nile, incluant le mobilier des stations et des installations opérationnelles. Livré selon les mêmes normes de qualité que le projet du monorail NCC."
  },
  {
    "slug": "five-star-hotel-project",
    "name": "5-Star Hotel Project",
    "name_ar": "مشروع فندق 5 نجوم",
    "name_it": "Progetto Hotel 5 Stelle",
    "name_fr": "Projet hôtel 5 étoiles",
    "sector": "Hospitality",
    "sector_ar": "الضيافة",
    "sector_it": "Ospitalità",
    "sector_fr": "Hôtellerie",
    "location": "Egypt",
    "location_ar": "مصر",
    "location_it": "Egitto",
    "location_fr": "Égypte",
    "image": "/images/partners-projects/able-hospitality-project.png",
    "description": "Turnkey hospitality furniture supply and installation for a prestigious 5-star hotel. Every piece was sourced from European manufacturers to match the property's interior design vision and deliver lasting luxury for guests.",
    "description_ar": "توريد وتركيب أثاث ضيافة متكامل لفندق 5 نجوم مرموق. تم استيراد كل قطعة من مصنعين أوروبيين لتتناسب مع رؤية التصميم الداخلي للمنشأة وتقديم فخامة تدوم للضيوف.",
    "description_it": "Fornitura e installazione chiavi in mano di mobili per l'ospitalità per un prestigioso hotel a 5 stelle. Ogni pezzo è stato acquistato da produttori europei per adattarsi alla visione del design degli interni della proprietà e offrire un lusso duraturo agli ospiti.",
    "description_fr": "Fourniture et installation clé en main de mobilier d'hôtellerie pour un hôtel 5 étoiles de prestige. Chaque pièce a été sourcée auprès de fabricants européens pour correspondre à la vision du design intérieur de l'établissement et offrir un luxe durable aux clients."
  }
];

module.exports = projects;
