const projects = [
  {
    slug: 'ncc-monorail-depot-buildings',
    name: 'NCC Monorail Depot Buildings',
    subtitle: 'Ergonomic and O&M Furniture',
    sector: 'Transport / Control Room',
    location: 'New Capital City · New Cairo · Nasr City',
    image: '/images/our-projects/ncc-monorail-depot-buildings/100_4840.jpg',
    description: 'Supply and installation of ergonomic and O&M furniture for the NCC Monorail Depot Buildings across three sites — New Capital City, New Cairo, and Nasr City. Furniture was specified to meet the demanding 24/7 operational requirements of depot environments, covering workstations, operator consoles, storage, and administrative areas throughout each facility.',
    gallery: [
      '/images/our-projects/ncc-monorail-depot-buildings/100_4840.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4664.JPG',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4665.JPG',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4666.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4667.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4668.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4670.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4671.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4672.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4673.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4675.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4676.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4677.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4678.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4679.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4680.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4681.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4682.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4683.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4684.JPG',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4685.JPG',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4686.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4690.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4691.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4692.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4693.JPG',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4694.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4695.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4696.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4697.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4698.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4699.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4700.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4701.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4702.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4703.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4705.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4707.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4708.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4709.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4710.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4711.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4712.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4713.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4714.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4715.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4716.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4717.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4718.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4719.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4720.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4721.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4722.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4723.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4724.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4725.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4726.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4727.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4728.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4729.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4730.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4731.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4732.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4733.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4735.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4736.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4737.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4738.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4739.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4740.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4741.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4742.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4743.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4744.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4745.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4746.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4747.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4748.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4749.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4750.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4752.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4753.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4754.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4755.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4757.jpg',
      '/images/our-projects/ncc-monorail-depot-buildings/100_4758.jpg'
    ]
  },
  {
    slug: 'west-nile-monorail-control-rooms',
    name: 'West Nile Monorail Control Rooms',
    sector: 'Control Room',
    location: 'Egypt',
    image: '/images/control-room.png',
    description: 'Ergonomic control room furniture for the West Nile monorail project. Custom-configured consoles and operator desks designed for continuous monitoring operations, built to the same exacting standards as the NCC project.'
  },
  {
    slug: 'ncc-monorail-furniture',
    name: 'NCC Monorail Furniture',
    sector: 'Transport',
    location: 'New Administrative Capital, Egypt',
    image: '/images/office.png',
    description: 'General furniture supply for the New Administrative Capital monorail project, covering station facilities, administrative offices, and operational areas throughout the network.'
  },
  {
    slug: 'west-nile-monorail-furniture',
    name: 'West Nile Monorail Furniture',
    sector: 'Transport',
    location: 'Egypt',
    image: '/images/office.png',
    description: 'Furniture supply for the West Nile monorail project, including station and operational facility furnishings. Delivered to the same quality standards as the NCC monorail project.'
  },
  {
    slug: 'five-star-hotel-project',
    name: '5-Star Hotel Project',
    sector: 'Hospitality',
    location: 'Egypt',
    image: '/images/partners-projects/able-hospitality-project.png',
    description: 'Turnkey hospitality furniture supply and installation for a prestigious 5-star hotel. Every piece was sourced from European manufacturers to match the property\'s interior design vision and deliver lasting luxury for guests.'
  }
];

module.exports = projects;
